# -*- coding: utf-8 -*-
"""test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bbPCx5-UdKPRAIQgehsFt4OyBEpLP_J
"""

print("hello everyone")